version: '3.8'

services:
  # ----------------------------------------
  # PostgreSQL Database
  # ----------------------------------------
  db:
    image: postgres:15-alpine
    container_name: playto_postgres
    restart: always
    environment:
      POSTGRES_USER: playtouser
      POSTGRES_PASSWORD: playtopass123
      POSTGRES_DB: playtodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ----------------------------------------
  # Redis (for Celery message brokering)
  # ----------------------------------------
  redis:
    image: redis:7-alpine
    container_name: playto_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
